### ISSUE TITLE
Cleanup of temporary marionette directory sometimes fails

### ISSUE THREAD

**Issue by eserte** [david-dick/firefox-marionette#14] opened 2021-12-30 15:31 UTC
In some situations the temporary directory /tmp/firefox_marionette_local_.......... is not removed after the using script terminated. This can be reproduced with a simple oneliner like
```
perl5.34.0 -MFirefox::Marionette -E '$fm=Firefox::Marionette->new;$fm->go("http://www.cpan.org");'
```
Adding `$fm->quit` seems to help in this situation. However, I see that a `DESTROY` method exists and it looks like it tries to cleanup this directory, but for some reason it fails.

**Comment by david-dick** [comment] 2021-12-30 19:39
Thanks for the test case.  Confirmed.  I'm a little busy at the moment, but will hopefully get some time to work on this soon.

**Comment by david-dick** [comment] 2022-01-02 22:57
Looks like this is caused by something going wrong in global destruction.  It also works fine if you define `my $fm` instead of a global variable.  Should be fixed now.

**Closed by david-dick** 2022-01-02 22:57 UTC
Labels: bug
